name: 'Docker Build & Push Action'
description: 'Builds a Docker image and pushes to a private registry with support for multiple tags'
author: 'Sean Smith'
inputs:
  image:
    description: 'Name of the Docker image'
    required: true
  tags:
    description: 'Tags override for Docker image'
    required: false
  registry:
    description: 'Target Docker registry'
    required: true
  dockerfile:
    description: 'Location of Dockerfile, if not Dockerfile in root directory'
    required: false
    default: 'Dockerfile'
  directory:
    description: 'Directory to run `docker build` from, if not project root'
    required: false
  buildArgs:
    description: 'Docker build arguments in format KEY=VALUE,KEY=VALUE'
    required: false
  username:
    description: 'Docker registry username'
    required: false
  password:
    description: 'Docker registry password'
    required: false
  gitHubOrg:
    description: 'GitHub organization to push image to (if not current)'
    required: false
  addLatest:
    description: 'Adds latest tag to auto-generated GitOps tag'
    required: false
    default: 'false'
outputs:
  imageFullName:
    description: 'Full name of the Docker image with registry prefix and tag suffix'
  imageName:
    description: 'Name of the Docker image with owner prefix'
  tags:
    description: 'Tags for the Docker image'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'anchor'
  color: 'blue'
