module.exports = {
  getInput: jest.fn(),
  setOutput: jest.fn(),
  setFailed: jest.fn(),
  info: jest.fn(),
  warning: jest.fn(),
  error: jest.fn(),
  debug: jest.fn(),
  notice: jest.fn(),
  getBooleanInput: jest.fn(),
  getMultilineInput: jest.fn(),
  exportVariable: jest.fn(),
  setSecret: jest.fn(),
  addPath: jest.fn(),
  startGroup: jest.fn(),
  endGroup: jest.fn(),
  group: jest.fn(),
  isDebug: jest.fn(),
  saveState: jest.fn(),
  getState: jest.fn(),
};
